In [2]:
import pandas as pd
import json

# AirBnB Dataset Analysis

In [3]:
#Read in AirBnB data sample
#Start with Listings Data
path='D:/Coding Projects/Springboard/Capstone/AirBnB/Toronto/listings.csv'
abb_list = pd.read_csv(path)
abb_list.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,1419,https://www.airbnb.com/rooms/1419,20180808031137,2018-08-08,Beautiful home in amazing area!,"This large, family home is located in one of T...",Visit Toronto with this fabulous furnished hom...,"This large, family home is located in one of T...",none,The apartment is located in the Ossington stri...,...,f,NaN,NaN,f,f,strict_14_with_grace_period,f,f,1,0.19
1,8077,https://www.airbnb.com/rooms/8077,20180808031137,2018-08-08,Downtown Harbourfront Private Room,Guest room in a luxury condo with access to al...,My husband and I are both artists. I give pain...,Guest room in a luxury condo with access to al...,none,NaN,...,f,NaN,NaN,f,f,strict_14_with_grace_period,f,t,2,1.56
2,10314,https://www.airbnb.com/rooms/10314,20180808031137,2018-08-08,Union Inn II (Leslieville),We offer a private room for two with a queen b...,"The 'union inn' offers a clean, spacious room ...",We offer a private room for two with a queen b...,none,Our charming adopted home of Leslieville is a ...,...,f,NaN,NaN,f,f,moderate,f,f,1,0.71
3,12604,https://www.airbnb.com/rooms/12604,20180808031137,2018-08-08,Seaton Village Parlour Bedroom,Comfortable sofa bed in airy main floor parlour.,Family of 4 (2 kids) plus a friendly dog open...,Comfortable sofa bed in airy main floor parlou...,none,NaN,...,f,NaN,NaN,f,f,moderate,f,f,1,NaN
4,17936,https://www.airbnb.com/rooms/17936,20180808031137,2018-08-08,Private Room in Downtown Toronto,"First of all, I'd like to say a BIG Thank You ...",Welcome! Charming walk-up apartment in Downto...,"First of all, I'd like to say a BIG Thank You ...",none,The building is central to so many great neigh...,...,f,NaN,NaN,f,f,strict_14_with_grace_period,f,f,2,1.18

In [4]:
abb_list.describe()

,id,scrape_id,thumbnail_url,medium_url,xl_picture_url,host_id,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,jurisdiction_names,calculated_host_listings_count,reviews_per_month
count,1.754200e+04,1.754200e+04,0.0,0.0,0.0,1.754200e+04,0.0,17540.000000,17540.000000,0.0,...,14039.000000,14040.000000,14035.000000,14041.000000,14032.000000,14033.000000,0.0,0.0,17542.000000,14315.000000
mean,1.683533e+07,2.018081e+13,NaN,NaN,NaN,6.267028e+07,NaN,4.478506,4.478506,NaN,...,9.635515,9.405484,9.755397,9.762837,9.641320,9.473455,NaN,NaN,3.791130,1.950937
std,7.578725e+06,4.972798e+00,NaN,NaN,NaN,5.967271e+07,NaN,10.010340,10.010340,NaN,...,0.798646,0.963120,0.704294,0.700338,0.708932,0.854359,NaN,NaN,7.754612,2.141343
min,1.419000e+03,2.018081e+13,NaN,NaN,NaN,1.565000e+03,NaN,0.000000,0.000000,NaN,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN,NaN,1.000000,0.010000
25%,1.125480e+07,2.018081e+13,NaN,NaN,NaN,1.274210e+07,NaN,1.000000,1.000000,NaN,...,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,NaN,1.000000,0.410000
50%,1.847656e+07,2.018081e+13,NaN,NaN,NaN,3.953265e+07,NaN,1.000000,1.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,1.000000,1.100000
75%,2.302324e+07,2.018081e+13,NaN,NaN,NaN,1.038567e+08,NaN,3.000000,3.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,3.000000,2.830000
max,2.758201e+07,2.018081e+13,NaN,NaN,NaN,2.081082e+08,NaN,128.000000,128.000000,NaN,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,67.000000,16.860000

In [46]:
abb_list['jurisdiction_names'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: jurisdiction_names, dtype: float64

In [43]:
#Next view the Calendar data
path='D:/Coding Projects/Springboard/Capstone/AirBnB/Toronto/calendar.csv'
abb_cal = pd.read_csv(path)
abb_cal.head()

   listing_id        date available    price
0      183522  2019-08-07         t  $180.00
1      183522  2019-08-06         t  $180.00
2      183522  2019-08-05         t  $180.00
3      183522  2019-08-04         t  $180.00
4      183522  2019-08-03         t  $180.00

# Yelp Dataset Analysis

Next we will open the Yelp dataset. This data comes from Yelp's Academic dataset, found here: https://www.yelp.com/dataset

The data is made available by Yelp in JSON format. 

(Insert more info here, and the Kaggle links with additional documentation).

In [3]:
#Read in Yelp Business dataset
path='D:/Coding Projects/Springboard/Capstone/Yelp/yelp_academic_dataset_business.json'
yelp_df = pd.read_json(path, lines=True)

In [13]:
yelp_df.head()

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,neighborhood,postal_code,review_count,stars,state
0,1314 44 Avenue NE,"{'BikeParking': 'False', 'BusinessAcceptsCredi...",Apn5Q_b6Nz61Tq4XzPdf9A,"Tours, Breweries, Pizza, Restaurants, Food, Ho...",Calgary,"{'Monday': '8:30-17:0', 'Tuesday': '11:0-21:0'...",1,51.091813,-114.031675,Minhas Micro Brewery,,T2E 6L6,24,4.0,AB
1,,"{'Alcohol': 'none', 'BikeParking': 'False', 'B...",AjEbIBw6ZFfln7ePHha9PA,"Chicken Wings, Burgers, Caterers, Street Vendo...",Henderson,"{'Friday': '17:0-23:0', 'Saturday': '17:0-23:0...",0,35.960734,-114.939821,CK'S BBQ & Catering,,89002,3,4.5,NV
2,1335 rue Beaubien E,"{'Alcohol': 'beer_and_wine', 'Ambience': '{'ro...",O8S5hYJ1SMc8fA4QBtVujA,"Breakfast & Brunch, Restaurants, French, Sandw...",MontrÃƒÂ©al,"{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",0,45.540503,-73.599300,La Bastringue,Rosemont-La Petite-Patrie,H2G 1K7,5,4.0,QC
3,211 W Monroe St,None,bFzdJJ3wp3PZssNEsyU23g,"Insurance, Financial Services",Phoenix,None,1,33.449999,-112.076979,Geico Insurance,,85003,8,1.5,AZ
4,2005 Alyth Place SE,{'BusinessAcceptsCreditCards': 'True'},8USyCYqpScwiNEb58Bt6CA,"Home & Garden, Nurseries & Gardening, Shopping...",Calgary,"{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ...",1,51.035591,-114.027366,Action Engine,,T2H 0N5,4,2.0,AB

In [15]:
#View list of cities
print(list(yelp_df.city.unique()))

['Calgary', 'Henderson', 'MontrÃƒÂ©al', 'Phoenix', 'Toronto', 'Mississauga', 'Avondale', 'Pittsburgh', 'Markham', 'Las Vegas', 'Cleveland', 'Monticello', 'Streetsboro', 'Sun Prairie', 'Cave Creek', 'Middlefield', 'Medina', 'Gilbert', 'Upper St Clair', 'Avalon', 'North York', 'Monroeville', 'Concord', 'Charlotte', 'Tolleson', 'Mesa', 'Kent', 'South Euclid', 'Surprise', 'Scottsdale', 'Woodbridge', 'Thornhill', 'Tempe', 'Gastonia', 'North Las Vegas', 'Rocky River', 'Glendale', 'Richmond Hill', 'North Randall', 'Peoria', 'Richfield', 'Laval', 'Brooklyn', 'Garfield Heights', 'Landau', 'las vegas', 'Goodyear', 'Mentor', 'Amherst', 'Matthews', 'Chagrin Falls', 'Montreal', 'Ajax', 'Laveen Village', 'Etobicoke', 'Lakewood', 'Scarborough', 'Madison', 'Oakville', 'Stouffville', 'Chandler', 'Monroe', 'Pleasant Hills', 'Brunswick', 'Fountain Hills', 'East Gwillimbury', 'Mount Holly', 'Longueuil', 'Fort Mill', 'Swissvale', 'Litchfield Park', 'Verona', 'Waxhaw', 'Paradise Valley', 'Fitchburg', 'Avon', 'Mayfield Heights', 'Dorval', 'Wesley Chapel', 'Brampton', 'Westlake', 'Champaign', 'Maple', 'Wexford', 'Bedford', 'Broadview Heights', 'Stow', 'Tuscola', 'Heidelberg', 'East Mississauga', 'Pepper Pike', 'Newmarket', 'Vaughan', 'Peninsula', 'Maricopa County', 'Waddell', 'Cramerton', 'Imperial', 'Pickering', 'Parma', 'St-Jerome', 'Urbana', 'Oka', 'Murrysville', 'Irwin', 'Paradise', 'University Heights', 'Blainville', 'Stoughton', 'Higley', 'Cheswick', 'Pineville', 'Moon Twp', 'Solon', 'Pointe-Claire', 'Brossard', 'Huntersville', 'Sainte-Julie', 'MESA', 'Millvale', 'Belmont', 'Fairlawn', 'Euclid', 'Homestead', 'Macedonia', 'Beachwood', 'San Tan Valley', 'Lasalle', 'Nobleton', 'Painesville', 'Allison Park', 'McMurray', 'Chesterland', 'Twinsburg', 'Strongsville', 'Mentor On the Lake', 'Kirtland', 'Aurora', 'Bridgeville', 'Cuyahoga Falls', 'Northfield', 'Oregon', 'Cornelius', 'Bolton', 'Anthem', 'North Ridgeville', 'Stanley', 'Springdale', 'Mayfield', 'Fairview Park', 'East York', 'Saint-Laurent', 'North Versailles', 'Woodmere', 'Oakland', 'West Mifflin', 'Youngtown', 'Davidson', 'Tallmadge', 'Sun City', 'Candiac', 'Whitby', 'DeForest', 'Dollard-Des-Ormeaux', 'Saint-Sauveur', 'Rosemere', 'Pitcairn', 'Wilmerding', 'clinton', 'Boisbriand', 'York', 'Lyndhurst', 'Chandler-Gilbert', 'Roosevelt', 'Hudson', 'Buckeye', 'Carnegie', 'Westmount', 'Coraopolis', 'Sainte-Anne-De-Bellevue', 'Outremont', 'Berea', 'Sainte-Therese', 'Waunakee', 'Laval, Pont Viau', 'Lawrenceville', 'RosemÃƒÂ¨re', 'Montreal-West', 'Moon', 'Chardon', 'De Forest', 'Olivos', 'Mirabel', 'Parma Heights', 'Lam', 'Chateauguay', 'Middleburg Heights', 'Dallas', 'Stallings', 'Trafford', 'Division No. 6', 'Bradfordwoods', 'Sewickley', 'Vanier', 'Middleton', 'Georgetown', 'Saint-Jerome', 'Boulder City', 'NorthEast Calgary', 'Brecksville', 'Thale', 'Lake Wylie', 'Penn Hills', 'Lowell', 'Glbert', 'North Royalton', 'Cecil', 'Robinson Township', 'Oakwood', 'Cross Plains', 'N Las Vegas', 'Braddock', 'St Martin', 'Canonsburg', 'LaSalle', 'Maple Heights', 'Castle Shannon', 'Indian Trail', 'Philo', 'McKees Rocks', 'Homer', 'Indian Land', 'Streetsville', 'Monona', 'West Homestead', 'N. Las Vegas', 'Brook Park', 'St. Jean Sur Richelieu', 'South Park Township', 'Brookline', 'Dollard-Des Ormeaux', 'Mantua', 'Sheffield Village', 'Mint Hill', 'Willowick', 'Avon Lake', 'Mount Albert', 'Kannapolis', 'Whitchurch-Stouffville', 'Fort  Mill', 'Frazer', 'Fort McDowell', 'Sainte-Marguerite-Esterel', 'Savoy', 'Highland Heights', 'Unionville', 'Boston Heights', 'Mahomet', 'Saint-Leonard', 'Oakmont', 'Brooklin', 'Sainte-Marguerite-du-lac-Masson', 'Kirkland', 'Brookpark', 'Pierrefonds', 'Saint-Lazare', 'Anjou', 'Stade', 'Noyan', 'King', 'Venetia', 'Bratenahl', 'Agincourt', 'Airdrie', 'peoria', 'Hinckley', 'Willoughby Hills', 'Verdun', 'Midland', 'West View', 'Lacolle', 'El Mirage', 'Harrisburg', 'Willoughby', 'Chestermere', 'Saint-Hubert', 'Guadalupe', 'Bay Village', 'Harrison City', 'Elyria', 'Schomberg', 'Spring Valley', 'Gibsonia', 'Plum', 'Nellis AFB', 'Cleveland Heights', 'Saint-Jean-sur-Richelieu', 'Bethel Park', 'Painesville Township', 'las Vegas', 'Mc Donald', 'New Kensington', 'Sun City West', 'Laveen', 'Seven Hills', 'Shawnessy', "L'ÃƒÅ½le-Perrot", 'Rocky View No. 44', 'Lachenaie', 'Richmond Heights', 'Etna', 'Shaker Heights', 'Saint-Bernard de Lacolle', 'Saint-Alphonse', 'Cottage Grove', 'Elk Grove Villa', 'Mount Lebanon', 'Leetsdale', 'Mont-Royal', 'Independence', 'Freyburg', 'Sharpsburg', 'Pheonix', 'Kennedy Township', 'Saint-JÃƒÂ©rÃƒÂ´me', 'King City', 'Train', 'Mc Kees Rocks', 'Lorain', 'Sainte-Genevieve', 'Clairton', 'toronto', 'Dollard-des-Ormeaux', 'Enterprise', 'Tega Cay', 'Carefree', 'Henderson (Green Valley)', 'National City', 'Oakwood Village', 'Las  Vegas', 'Saint-Eustache', 'Nellis Afb', 'McCandless', 'Rocky View', 'COLUMBIA STA', 'Jork', 'Munroe Falls', 'Downtown', 'Casablanca', 'Montreal-Nord', 'Saint-Philippe', 'Mc Farland', 'Aspinwall', 'North Olmsted', 'Sagamore Hills', 'Willowdale', 'Southeast Calgary', 'Claremont', 'Ahwatukee', 'Duquesne', 'Bainbridge', 'Warrensville Heights', 'McKeesport', 'Eastlake', 'Vimont', 'Ambridge', 'St Joseph', 'Sainte-Madeleine', 'Haus', 'Burton', 'Saint-Lambert', 'Brentwood', 'Vaudreuil-Dorion', 'Fitchburgh', 'Lachine', 'C Las Vegas', 'Lachute', 'Joliette', 'Morin-Heights', 'Ross Township', 'Peninsul', 'Clark', 'Downsview', 'Montreal-Ouest', 'Lich', 'Orange Village', 'Rankin', 'Bradford', 'White Oak', 'Cuyahoga Fls', 'North Huntingdon', 'Bellevue', 'Monongahela', 'Baldwin', 'East Pittsburgh', 'Lower Burrell', 'Chambly', 'Presto', 'Cave Creek Road', 'Phoenix AZ', 'Downtown Toronto', 'Point-Claire', 'Newbury', 'Oakdale', "Notre-Dame-De-L'ile-Perrot", 'Turtle Creek', 'Upper St. Clair', 'McAdenville', 'Sainte-Catherine', 'Olmsted Township', 'Bedford Heights', "L'ile-Perrot", 'Dane', 'Moss', 'Cooksville', 'Balzac', 'Mentor On the', 'Terrebonne', 'Palgrave', 'Paoli', 'Grand River', 'Kinsman', 'Phoenix,', 'Kleinburg', 'North Scottsdale', 'South Park', 'Munhall', 'Gifford', 'Valley View', 'Scottdale', 'Indianola', 'Saint-Bruno', 'Saint-Sauveur-des-Monts', 'Pittsburg', 'Mansfeld', 'South Hills', 'GrÃƒÂ¼nberg', 'Saint-Hyacinthe', 'Concord Township', 'Southern', 'Desert Ridge', 'Northfield Center', 'Saint-Marc-Sur-Richelieu', 'Massey', 'Carp', 'Ormstown', 'North Huntington', 'Repentigny', 'South Amherst', 'Crafton', 'Dravosburg', 'Sankt Martin', 'Piedmont', 'Mount Horeb', 'Mt Lebanon', 'Rouses Point', 'Glenshaw', 'Venise-En-Quebec', 'Bellvue', 'Caledon', 'Las vegas', 'Maria', 'Medina Township', 'N Ridgeville', 'Sainte-Marthe', 'Ogden', 'Library', 'Queensville', 'Pointe Claire', 'Phoenix, AZ', 'columbia station', 'La Prairie', 'Gormley', 'Summerlin', 'Cuyahoga Heights', 'Hampton Township', 'Cote-Saint-Luc', 'Saint-Hippolyte', 'Inden', 'Windsor', 'Pickering Ajax Whitby', 'Silver Lake', 'Landsberg', 'Rosewood', 'Edgeworth', 'Sainte-Anne-de-Bellevue', 'Wilkinsburg', 'Enns', 'Overbrook', 'North  York', 'Don Mills', 'Chander', 'Copley', 'Orange', 'Pointe-Aux-Trembles', 'Phoniex', 'Rexdale', 'St. LÃƒÂ©onard', 'Ferrel', 'Wilkins Township', 'Boucherville', 'Sun Lakes', 'New Eagle', 'Pfaffing', 'Concord Twp', 'Wickliffe', 'Grafton', 'Nellis Air Force Base', 'Midnapore', 'Black Earth', 'Saint Joseph', 'Finleyville', 'Sevilla', 'Clinton', 'Whitney', 'Fox Chapel', 'Beauharnois', 'Central City Village', 'Glassport', 'Herminie', 'The Promenade', 'Stowe', 'Mt Holly', 'Walton', 'Mayfield Village', 'Las Vegass', 'Allegheny', 'East Cleveland', 'Lagrange', 'CommunautÃƒÂ©-Urbaine-de-MontrÃƒÂ©al', 'Elizabeth Township', 'Rantoul', 'Strongville', 'Mentor-on-the-Lake', 'Fairview', 'SouthWest Calgary', 'McFarland', 'Blue Diamond', 'Scottsale', 'East Mesa', 'SW Calgary', 'Inglewood', 'Saint-Jean-Sur-Richelieu', 'Saint Laurent', 'NORTH YORK', 'Middleburg', 'Olmsted Falls', 'Russellton', 'Westworld Scottsdale', 'Jefferson Hills', 'LasVegas', 'Central Oakland', 'Las Vegas East', 'Mayfield Hts.', 'SouthEast Calgary', 'MATTHEWS', 'Thorncliffe Park', 'Hiram', 'Dollard-des Ormeaux', 'Nottingham', 'MADISON', 'Upper Saint Clair', 'Beloeil', 'Wildwood', 'Phx', 'Tornoto', 'Waterford', 'Caregie', 'Moon Township', 'Bellagio', 'Brampton FKA Bramalea', 'Sheffield Lake', 'Indus', 'The Woodlands', '', 'Saint-Constant', 'Sturgeon', 'East Ajax', 'Fithian', 'Estrella Village', 'Houston', 'Bradford West Gwillimbury', 'Chateau', 'Ben Avon', 'Bedford HTS', 'Creighton', 'East Credit', 'Harmarville', 'Phoneix', 'Liberty', 'North Olmstead', 'Glendale Az', 'East Mc Keesport', 'McDonald', 'Jessen', 'S Concord', 'Chester Township', 'Weston', 'Villa Rosa', 'Caledon East', 'Mansfield', 'Blawnox', 'Palmerston', 'Litchfield', 'Greenfield Park', 'Ville Mont-Royal', 'highland hts', 'Beaconsfield', 'Thornhil', 'Caledon Village', 'Sage Hill', 'San Gennaro', 'Phonenix', 'Schottsdale', 'Elizabeth', 'Bedford Hts.', 'Arnold', 'Squirrel Hill', 'Moreland Hills', 'Shaler', 'St. Peters', 'Shaker Hts', "L'assomption", 'Novelty', 'Rawdon', 'CHARLOTTE', 'Thomasboro', 'Vinci', 'Auburn Township', 'Angus', 'kirkwood', 'Hermitage Twp', 'Warrensville Hts', 'Etobiicoke', 'Dormont', 'Ste-Therese-de-Blainville', 'charlottte', 'WICKLIFFE', 'Mccandless Township', 'Mont-Saint-Hilaire', 'McCandless Township', 'Scarbrough', 'Brooklyn Heights', 'Robinson', 'McMurry', 'Strip District', 'NC', 'Sainte-GeneviÃƒÂ¨ve', 'Port Credit', 'East Calgary', 'Saint-Bruno-de-Montarville', 'Mt. Holly', 'ChÃƒÂ¢teauguay', 'Rainbow Valley', 'Gelndale', 'Chomedey, Laval', 'etobicoke', 'Auburn', 'Fairport Harbor', 'Norland', 'Cote Saint-Luc', 'Weddington', 'South Las Vegas', 'East Liberty', 'Warrensville', 'Henderson, NV', 'Suite 120', 'Stetson Valley', 'Blakeney', 'North Braddock', 'Lowesville', 'Topaz', 'Tigre', 'Argos', 'Mentor On The Lake', 'La Baie', 'Ross', 'Columbia Station', "L'ile-Bizard", 'Shaler Township', 'Berry', 'Forest Hills', 'Mc Murray', 'Fabreville', 'Northwest Calgary', 'Alburg', 'Springfield', 'Yorkdale', 'Missisauga', 'ÃƒÅ½le des Soeurs', 'Tolono', 'Etobicoke,', 'Sheffield', 'Richmond Hts', 'N. Ridgeville', 'Larimer', 'Garfield Hts', 'Suncity', 'Ft. Mill', 'Hendersonville', 'Vegas', 'St. Sauveur', 'N. Randall', 'The Quay', 'Lindale', 'Ingomar', 'Rain', 'Mint  Hill', 'San Rafael', "L'Ile-Perrot", 'University Ht', 'Sainte-AdÃƒÂ¨le', 'Mooers', 'Peoria, AZ', 'Plan', 'Totronto', 'Edgewood', 'Marvin', 'Roxboro', 'Salaberry-De-Valleyfield', 'Elrama', 'Ranlo', 'Bayview', 'Green Tree', 'South Charlotte', 'Saint-Georges', 'Crescent', 'Scott Township', 'tempe', 'Delson', 'Chatauguay', 'Kettleby', 'Central Henderson', 'Municipality of Murrysville', 'Ingram', 'Boston', 'Vaughn', 'SCARBOROUGH', 'Fisher', 'Middleburg Hts', 'Indian land', 'Phoenix metro area', 'Southside Flats', 'Wendel', 'Los Molinos', 'Richmond Height', 'Sainte-Adele', 'San Tan', 'Sloan', 'Mascouche', "Baie-D'urfe", 'Metro Phoenix', 'Vilas', 'Belleville', 'East McKeesport', 'Ville-Marie', 'Buena Vista', 'St-Leonard', 'Lake Las Vegas', 'Harwick', 'Napierville', 'Sainte-Anne-des-Plaines', 'Mt. Lebanon', 'Warrensville Hts.', 'Ballantyne', 'Camargo', 'Bright', 'Lakewood, Oh', 'Scotsdale', 'Geauga', 'NorthYork', 'Bainbridge Township', 'Shady Side', 'Oakridges', 'Cuddy', 'N. OLMSTED', 'EstÃƒÂ©rel', 'Brunswick Hills', 'N W Las Vegas', 'Valley City', 'Cleveland, OH', 'Farnham', 'Skara', 'Ridgeville', 'Turks and Caicos Islands', 'Bloomfield', 'North Olmsted,', 'Median', 'Scottsdale, AZ', 'Peters Township', 'Mont-Saint-Gregoire', 'Gillbert', 'Neville Island', 'Cote Saint Luc', 'Linden', 'Hendserson', 'N E Las Vegas', 'Rocky View County', 'St Davids', 'Davidson, Nc', 'Franklin Park', 'NorthWest Calgary', 'MontÃƒÂ©al', 'Centennial Hills', 'Scarborough,', 'W Henderson', 'Morgan', 'Clarkson', 'Etobicoke On', 'Garfield hts', 'Broadlands', 'Saint-Basile-Le-Grand', 'Las Vegas,', 'North  Ridgeville', 'Ashburn', 'Spa', 'Pittsburch', 'Bond Head', 'Township of Concord', 'Bentleyville', 'Side Slopes', 'Green Valley', 'Whiitby', 'Rillton', 'MontrÃƒÂ©al-Nord', 'Glamorgan', 'Otterburn Park', 'Harmar Township', 'Leaside', 'Mercier', 'Ville Saint Laurent', 'Churubusco', 'Broadview Hts', 'Plum Boro', 'Northifield', 'Saint-Charles-Borromee', 'Beltline', 'St-Sauveur', 'MontrÃƒÂ©al (QuÃƒÂ©bec)', 'Mississauaga', 'Nellis', 'Robinson Twp.', 'Promenade', 'La Vegas', 'Decatur', 'Old Scottsdale', 'Moon Twp.', 'Pepperpike', 'Ste-Rose', 'Buckeye - Shaker', 'Gates Mills', 'Champlain', 'Pointe-Calumet', 'La Salle', 'Mt. Oliver Boro', 'Kahnawake', 'Cleveland Height', 'St Oswald', 'Tornto', 'Mount Laurel', 'Lavaltrie', 'Mt Albert', 'Mckeesport', 'Saint-Marc-sur-Richelieu', 'St Leonard', 'Centre Island', 'Northfield Center Township', 'FORT MILL', 'Sainte-Marguerite-du-Lac-Masson', 'River Drive Park', 'Superstition Mountain', 'Bath', 'Old Port of Montreal', 'Toronto Division', 'Oak Ridges', 'Saint-Charles-BorromÃƒÂ©e', 'Wilkens Township', 'Sainte-thÃƒÂ©rÃƒÂ¨se', 'Suprise', 'Emsworth', 'St-Clet', 'Phoenix Valley', 'Pincourt', 'Saint-Pierre-de-VÃƒÂ©ronne-Ãƒ\xa0-Pike-River', 'Deux-Montagnes Regional County Municipality', 'vaughan', 'North of Brampton', 'Mississauge', 'Cardinal', 'Holland Landing', 'MontrÃƒÂ©al-Ouest', 'Central City', 'Lawrence', 'Glen Williams', 'Summerlin South', 'Midddleton', 'Newburgh Heights', 'Mount Washington', 'Huntingdon', 'Queens Square', 'Ahwahtukee', 'St-Jean-sur-Richelieu', 'Charlotte NC', 'Indian Land,', 'Tallinn', 'Pasadena', 'Shadyside', 'Bois-Des-Filion', 'Penn Hills Township', 'Mc Adenville', 'McMasterville', 'Highland Park', 'AGINCOURT', 'Sainte-ThÃƒÂ©rÃƒÂ¨se-de-Blainville', "Peoria Ave Citizen's Group", 'Mount Mourne', 'Surprise Crossing', 'Wood Dale', 'Ange-Gardien', 'Lower Lawrenceville', 'Mesa AZ', 'Mayfield Heights (Cleveland)', 'West Elizabeth', 'Iberville', 'St-BenoÃƒÂ®t de Mirabel', 'Toronto-North York', 'Mississuaga', "L'ÃƒÅ½le-Bizard", 'Auburn Twp', 'Russell Twp', 'Varennes', 'Concord Mills', 'Old Town Scottsdale', 'Sainte-Rose', 'Laval, Ste Dorothee', 'Stoney Creek', "L'ÃƒÅ½le-PerrÃƒÂ´t", 'Ste-DorothÃƒÂ©e', 'Twinsburgh', 'Richmonhill', 'Maple Grove', 'Coteau-Du-Lac', 'Sunnyslope', 'Bell', 'Rural Ridge', 'Mcmurray', 'Goodwood', 'West Toronto', 'Montreal-Quest', 'Auerbach', 'Bro', 'Canyon Village', 'Cleveland Hghts.', 'lachine', 'CÃƒÂ´te-Saint-Luc', 'Royal', 'Highland Hills', 'oakville', 'Edgewater', 'Saint-Isidore-De-Laprairie', 'W Spring Valley', 'Saint-Pie', 'Godmanchester', 'Wharton', 'Indian Lands', 'Henderson Nevada', 'Sainte-ThÃƒÂ©rÃƒÂ¨se', '110 Las Vegas', 'Ansnorveldt', 'Regent Square', 'Lake Norman', 'Fullerton', 'York Regional Municipality', 'Tottenham', 'Ahwatukee Foothills Village', 'Scotesdale', 'Middleburg Hts.', 'Brettin', 'Saint-Bernard-de-Lacolle', 'Le Sud-Ouest', 'Arrowhead', 'Saint-sauveur', 'Norval', 'Phoeniix', 'Montrose', 'ÃƒÅ½le-des-Soeurs', 'mesa', 'Las Vegas Nv', 'Rockyview', 'Shorewood Hills', 'Richmond', 'Mayfield Hts', 'Beeton', 'frazer', 'Rigaud', 'Dewey', 'Lake Park', 'Catawba Springs', 'Vaudreuil', 'Rougemont', 'Northbrook', 'Banksville', 'Sunrise', 'Troy Township', 'Citibank', "Baie-d'UrfÃƒÂ©", 'Hawthorne', 'East Gwilimbury', 'St-Bruno-de-Montarville', 'Las Vegas & Henderson', 'St-EugÃƒÂ¨ne', 'Northeast Calgary', 'CARSON', 'Warrenville', 'Whtiby', 'Scarobrough', 'St-Lazare', 'Monoroeville', 'Montral', 'Scarborough (C)', 'St-Laurent', 'Sidney', 'Lindberg', 'Mt. Washington', 'Mathews', 'Canning', 'SLOAN', 'Alburgh', 'Char', 'Saint Leonard', 'Henderston', 'Saint-Henri', 'Old Brooklyn', 'Toronto-West', 'Regional Municipality of York', 'CITY CENTER', 'Port Vue', 'Paw Creek', 'North Toronto', 'Lambton', 'Tempe, AZ 85283', 'Moneroeville', 'Alberta Park Industrial', 'Mayfield Heights.', 'PrÃƒÂ©vost', 'Pgh Int Arprt', 'CALGARY', 'V', 'Toronto-Etobicoke', 'Huntsburg', 'Mesa Arizona', 'Pheonix AZ', 'Yukon', 'Forest Grove', 'Malton', 'Murrysville (Monroeville)', "Saint-Roch-De-L'achigan", 'Sainte-Marie', 'Clark County', 'Edgemont', 'SP', 'West Bridgewater', 'Hampstead', 'Lingen', 'Brooklyn Hts.', 'West Las Vegas', 'Villa Grove', 'Saint - Hyacinthe', 'Tremont', "MontrÃƒÂ©al De L'aube", 'Les Coteaux', 'Northside', 'Las Vegas, NV', 'Harrisbug', 'Chertsey', 'West MontrÃƒÂ©al', 'Hemmingford', 'Richland Township', 'Bois-des-Filion', 'Walton Hills', 'City Bell', 'Westview', 'Charlemagne', 'Toronto Scarborough', 'Saint-Bernard-De-Lacolle', 'Woodmere Village', 'Onda', 'McKnight', 'Mt. Horeb', 'Canonsburd', 'Mattews', 'Main Street', 'Las Vegas Nevada', 'montreal', 'Richmond Hil', 'University Hts ', 'MC Murray', 'Mont St-hilaire', 'Woodbridge (Vaughan)', 'Monreoville', 'Sainte-DorothÃƒÂ©e', 'Nottingham Township', 'Pine', 'Le Haut-Saint-Laurent Regional County Municipality', 'Austin', 'Spring Hill City View', 'Harrisburg,', 'Henderson and Las vegas', 'Leslieville', 'Parma mid birth', "O'hara Township"]

In [38]:
#There are too many cities to view this way,
#...instead let's look for the top 10 cities in the dataset

city_count = yelp_df['city'].value_counts().to_frame().reset_index().sort_values('city', ascending=False)

city_count.head(10)

        index   city
0   Las Vegas  28865
1     Phoenix  18633
2     Toronto  18233
3   Charlotte   9204
4  Scottsdale   8822
5     Calgary   7384
6  Pittsburgh   6804
7        Mesa   6239
8   MontrÃƒÂ©al   6045
9   Henderson   4815